In [ ]:
# 1. Student Grades Analysis
# You are given a 2D NumPy array grades where each row represents a student, and each column represents their score in a subject.


# grades = np.array([
#     [85, 90, 78, 92],
#     [88, 76, 85, 80],
#     [70, 65, 60, 75],
#     [90, 92, 94, 96]
# ])
# Tasks:
# Find the average score for each student.
# Find the average score per subject.
# Identify which students scored below 80 in all subjects.
# Add 5 bonus points to students who scored below 70 in any subject.
# Find the total and standard deviation of scores per student.

In [9]:
import numpy as np
grades = np.array([
    [85, 90, 78, 92],
    [88, 76, 85, 80],
    [70, 65, 60, 75],
    [90, 92, 94, 96]
])
avg_score=np.average(grades,axis=1)
print(avg_score)
avg_score2=np.average(grades,axis=0)
print(avg_score2)
# Identify which students scored below 80 in all subjects.
print(grades[np.all(grades<80,axis=1)])
# Add 5 bonus points to students who scored below 70 in any subject.
# print(grades[grades<70]+5) wrong
copy_grades=grades.copy()
copy_grades[np.any(copy_grades<70)]+=5
print(copy_grades)
# Find the total and standard deviation of scores per student.
marks=np.sum(grades,axis=1)
print(marks)
sd=np.std(grades,axis=1)
print(sd)

[86.25 82.25 67.5  93.  ]
[83.25 80.75 79.25 85.75]
[[70 65 60 75]]
[[ 90  95  83  97]
 [ 93  81  90  85]
 [ 75  70  65  80]
 [ 95  97  99 101]]
[345 329 270 372]
[5.4025457  4.60298816 5.59016994 2.23606798]


In [15]:
# 2. Weather Data Processing
# Given temperature readings (in Celsius) over 7 days in 3 different cities:
# temps = np.array([
#     [30, 32, 31, 29, 28, 27, 30],  # City A
#     [25, 26, 24, 23, 22, 24, 25],  # City B
#     [35, 36, 34, 33, 32, 31, 30]   # City C
# ])
# Tasks:
# Convert all temperatures to Fahrenheit (use formula: F = C * 9/5 + 32).
# Find the maximum and minimum temperature for each city.
# Determine on which days City A had higher temperature than City C.
# Find the average weekly temperature for each city.

In [ ]:
import numpy as np
temps = np.array([
    [30, 32, 31, 29, 28, 27, 30],  # City A
    [25, 26, 24, 23, 22, 24, 25],  # City B
    [35, 36, 34, 33, 32, 31, 30]   # City C
])
# Convert all temperatures to Fahrenheit (use formula: F = C * 9/5 + 32).
f=temps*9/5+32
print(f)
# Find the maximum and minimum temperature for each city.
maxi=np.max(temps,axis=1)
mini=np.min(temps,axis=1)
print(maxi)
print(mini)
# Find the average weekly temperature for each city.
avg_temp=np.average(temps,axis=1)
print(avg_temp)
# Determine on which days City A had higher temperature than City C.
np.all(temps[temps[0]>temps[2]])



[[86.  89.6 87.8 84.2 82.4 80.6 86. ]
 [77.  78.8 75.2 73.4 71.6 75.2 77. ]
 [95.  96.8 93.2 91.4 89.6 87.8 86. ]]
[32 26 36]
[27 22 30]
[29.57142857 24.14285714 33.        ]
[False False False False False False False]


<!-- 3. Sales Commission Tracker
A salesperson has weekly sales data for 4 weeks across 5 different products:

sales = np.array([
    [200, 180, 220, 240, 210],
    [250, 260, 210, 200, 190],
    [300, 310, 320, 330, 340],
    [150, 140, 130, 120, 110]
])
Tasks:
Calculate the total sales per product.
Find the week with the highest total sales.
Calculate the cumulative sales for each product.
Identify the products whose average sales exceeded 250.
Normalize sales data to a 0–1 scale using min-max scaling. -->

In [ ]:
sales = np.array([
    [200, 180, 220, 240, 210],
    [250, 260, 210, 200, 190],
    [300, 310, 320, 330, 340],
    [150, 140, 130, 120, 110]
])
# Calculate the total sales per product.
sales_product=np.sum(sales,axis=0)
print(sales_product)
# Find the week with the highest total sales.
sales_week=np.sum(sales,axis=1)
max_sales=np.max(sales_week,axis=0)
print(sales_week)
print(max_sales)
print(f" week with maximum sales is{np.argmax(sales_week)+1}")
# Calculate the cumulative sales for each product.
cum_sale=np.cumulative_sum(sales,axis=0)
print(cum_sale)


[900 890 880 890 850]
[1050 1110 1600  650]
1600
 week with maximum sales is3


<!-- 4.Employee Salary Analysis
You are given the salary data of employees over 4 months:
salaries = np.array([
    [45000, 47000, 49000, 51000],
    [40000, 42000, 44000, 46000],
    [60000, 62000, 64000, 66000],
    [38000, 39000, 41000, 43000]
])
Tasks:

Find the total salary paid to each employee.
Compute the average salary per month.
Identify employees who always earned more than 40,000.
Add a bonus of 2000 to all employees but cap the max salary to 65,000.
Normalize the salary data to a 0–1 scale. -->

In [10]:
import numpy as np
salaries = np.array([
    [45000, 47000, 49000, 51000],
    [40000, 42000, 44000, 46000],
    [60000, 62000, 64000, 66000],
    [38000, 39000, 41000, 43000]
])
# Find the total salary paid to each employee.
esal=np.sum(salaries,axis=1)
print(esal)
# Compute the average salary per month.
avgsalry=np.average(salaries,axis=1)
print(avgsalry)
# Identify employees who always earned more than 40,000.
mask=np.all(salaries>40000,axis=1)
print(mask)
# print(np.all(salaries[mask],axis=1))
# np.all(salaries[mask],axis=1)
print(salaries[mask])
#Add a bonus of 2000 to all employees but cap the max salary to 65,000.
# salaries+2000
print(np.clip(salaries+2000,0,65000))



[192000 172000 252000 161000]
[48000. 43000. 63000. 40250.]
[ True False  True False]
[[45000 47000 49000 51000]
 [60000 62000 64000 66000]]
[[47000 49000 51000 53000]
 [42000 44000 46000 48000]
 [62000 64000 65000 65000]
 [40000 41000 43000 45000]]


<!-- 3. Product Sales Tracker
python
Copy
Edit
sales = np.array([
    [10, 15, 20],
    [25, 30, 35],
    [40, 45, 50],
    [55, 60, 65]
])
Tasks: row repesents weels and column represent product

Find the total sales per product.
Determine the week with the highest sales.
Calculate the percentage of products that sold over 40 units.
Perform min-max normalization across the full matrix.
Replace all sales below 30 with 0 using masking. -->

In [14]:
import numpy as np
sales = np.array([
    [10, 15, 20],
    [25, 30, 35],
    [40, 45, 50],
    [55, 60, 65]
])
productsales=np.sum(sales,axis=0)
print(productsales)
# Determine the week with the highest sales
print(np.argmax(np.sum(sales,axis=1)))
# Calculate the percentage of products that sold over 40 units.
sales40=sales>40
count1=np.sum(sales40)
totalsales=np.size(sales)
print(count1/totalsales *100)


[130 150 170]
3
41.66666666666667
