In [4]:
import numpy as np
temps = np.array([35.5, 36.1, 37.8, 39.2, 38.0, 36.5, 35.0, 40.1, 37.0, 38.5])
# Find how many temperatures are above 38°C.

# Extract all temperature readings between 36°C and 38°C.

# Convert all the temperatures to Fahrenheit.
t=temps>38
print(t)
tt=temps[t]
print(tt.size)


[False False False  True False False False  True False  True]
3


In [ ]:
scores = np.array([
    [45, 78, 82],
    [92, 88, 95],
    [55, 61, 60],
    [30, 40, 38]
])
# Find the average score for each student.
# Select all students who scored more than 60 in all subjects.
# Increase each student's scores by 5 bonus points, but cap the max score at 100.
avg=np.mean(scores)
student=scores>60  #check all the values and give true and false
print(student)
print(np.all(scores>60,axis=1)) # axis =1 mean it will check for all values in a row and return truw for a row if all values follow the consition and we will have a 1 d array representing which rows completely follow the condition
print(scores[np.all(scores>60,axis=1)]) # it takes a 1 d array and put gives rows is score which represent true
marks=scores+5
print(marks)
print(avg)

In [16]:
sales_q1 = np.array([12000, 15000, 18000, 17000])
sales_q2 = np.array([13000, 16000, 17500, 19000])
# Calculate absolute growth for each region.
# Calculate percentage growth.
# Identify which regions had over 10% growth.
absolutegrowth=sales_q2-sales_q1
print(absolutegrowth)
percentage_growth=(sales_q2-sales_q1)/sales_q1 *100
print(percentage_growth)
reigon=percentage_growth>10
print(sales_q1[reigon])


[1000 1000 -500 2000]
[ 8.33333333  6.66666667 -2.77777778 11.76470588]
[17000]


In [ ]:
image = np.array([
    [100, 150, 200],
    [120, 180, 220],
    [90,  140, 240]
])
#You have a grayscale image represented as a 3x3 array:
# Find all pixel values greater than 180.
pixel30=image[image>180]
print(pixel30)
# Replace all values > 180 with 180 (simulate contrast limiting).

# Flatten the image into a 1D array.
print(image.flatten())



[200 220 240]
